import { render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import type { ReactNode } from 'react'
import { LedgerCharts } from './LedgerCharts'
vi.mock('recharts', () => ({ ResponsiveContainer: ({ children }: { children: ReactNode }) => <div>{children}</div>, BarChart: ({ children }: { children: ReactNode }) => <div>{children}</div>, LineChart: ({ children }: { children: ReactNode }) => <div>{children}</div>, PieChart: ({ children }: { children: ReactNode }) => <div>{children}</div>, Pie: () => null, Bar: () => null, Line: () => null, CartesianGrid: () => null, Legend: () => null, Tooltip: ({ contentStyle }: { contentStyle?: { backgroundColor?: string; border?: string } }) => <output data-testid="monolith-chart-tooltip" data-background={contentStyle?.backgroundColor} data-border={contentStyle?.border} />, XAxis: () => null, YAxis: () => null }))
describe('LedgerCharts', () => {
  it('renders localized category and six-month evolution chart labels', () => { render(<LedgerCharts categories={[{ categoryId: 1, categoryName: 'Mercado', spent: 120 }]} evolution={[{ month: '2026-08', income: 1000, expense: 120 }]} />); expect(screen.getByRole('heading', { name: 'Gastos por categoria' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Evolução dos últimos seis meses' })).toBeInTheDocument(); expect(screen.getByLabelText('Gráfico de barras de gastos por categoria')).toBeInTheDocument() })
  it('provides a textual solid-income and dashed-expense legend', () => { render(<LedgerCharts categories={[]} evolution={[{ month: '2026-08', income: 1000, expense: 120 }]} />); const legend = screen.getByRole('list', { name: 'Legenda do fluxo financeiro' }); expect(legend).toHaveTextContent('Rendas — linha sólida'); expect(legend).toHaveTextContent('Despesas — linha tracejada'); expect(screen.getByText('R$ 1.000,00')).toBeInTheDocument() })
  it('renders a monochrome expense donut with central total and only the top three categories', () => { render(<LedgerCharts categories={[{ categoryId: 1, categoryName: 'Moradia', spent: 300 }, { categoryId: 2, categoryName: 'Mercado', spent: 200 }, { categoryId: 3, categoryName: 'Transporte', spent: 100 }, { categoryId: 4, categoryName: 'Outros', spent: 50 }]} evolution={[]} />); expect(screen.getByLabelText('Donut de despesas por categoria')).toBeInTheDocument(); expect(screen.getByText('R$ 650,00')).toBeInTheDocument(); const list = screen.getByRole('list', { name: 'Três maiores despesas por categoria' }); expect(list).toHaveTextContent('Moradia'); expect(list).toHaveTextContent('Transporte'); expect(list).not.toHaveTextContent('Outros') })
  it('styles chart tooltips for the Monolith surface', () => { render(<LedgerCharts categories={[{ categoryId: 1, categoryName: 'Mercado', spent: 120 }]} evolution={[{ month: '2026-08', income: 1000, expense: 120 }]} />); expect(screen.getAllByTestId('monolith-chart-tooltip')).toHaveLength(2); expect(screen.getAllByTestId('monolith-chart-tooltip')[0]).toHaveAttribute('data-background', '#18181a') })
})
