import { type FormEvent, useEffect, useState } from 'react'
import { createTransaction, getCategories } from '../lib/api'
import type { Category } from '../types/api'

export function ManualTransactionForm({ onCreated }: { onCreated: () => void }) {
  const [categories, setCategories] = useState<Category[]>([]); const [error, setError] = useState<string | null>(null)
  useEffect(() => { getCategories().then(setCategories).catch(() => setError('Unable to load categories.')) }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); const data = new FormData(event.currentTarget); try { await createTransaction({ date: String(data.get('date')), description: String(data.get('description')), amount: Number(data.get('amount')), categoryId: String(data.get('categoryId')), type: String(data.get('type')) as 'EXPENSE' | 'INCOME' | 'INVESTMENT' }); event.currentTarget.reset(); onCreated() } catch { setError('Unable to add transaction. Please try again.') } }
  return <section aria-labelledby="manual-transaction-heading" className="rounded border bg-white p-4"><h2 id="manual-transaction-heading" className="text-xl font-semibold">Add transaction</h2>{error && <p role="alert">{error}</p>}<form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={submit}><label>Date<input className="block w-full border p-2" name="date" required type="date" /></label><label>Description<input className="block w-full border p-2" name="description" required /></label><label>Amount<input className="block w-full border p-2" name="amount" required step="0.01" type="number" /></label><label>Category<select className="block w-full border p-2" name="categoryId" required>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Type<select className="block w-full border p-2" name="type"><option value="EXPENSE">Expense</option><option value="INCOME">Income</option><option value="INVESTMENT">Investment</option></select></label><button className="rounded bg-slate-900 px-4 py-2 text-white" type="submit">Add transaction</button></form></section>
}
