CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    system_category BOOLEAN NOT NULL,
    user_id BIGINT,
    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

INSERT INTO categories (name, system_category, user_id) VALUES
    ('Alimentação', TRUE, NULL),
    ('Transporte', TRUE, NULL),
    ('Mercado/Compras', TRUE, NULL),
    ('Investimentos', TRUE, NULL),
    ('Outros', TRUE, NULL);
