CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    history VARCHAR(255),
    description VARCHAR(255),
    normalized_description VARCHAR(255) NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    duplicate_fingerprint VARCHAR(64),
    needs_review BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_transactions_user_date ON transactions (user_id, transaction_date);
CREATE INDEX idx_transactions_duplicate ON transactions (user_id, transaction_date, amount);

CREATE TABLE category_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    normalized_description VARCHAR(255) NOT NULL,
    CONSTRAINT fk_category_rules_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_category_rules_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT uq_category_rules_user_description UNIQUE (user_id, normalized_description)
);
