CREATE TABLE savings_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    target_amount NUMERIC(19,2) NOT NULL,
    target_date DATE,
    CONSTRAINT fk_savings_goals_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE TABLE savings_goal_months (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    reference_month DATE NOT NULL,
    planned_amount NUMERIC(19,2) NOT NULL,
    saved_amount NUMERIC(19,2) NOT NULL,
    CONSTRAINT fk_savings_goal_months_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_savings_goal_months_goal FOREIGN KEY (goal_id) REFERENCES savings_goals(id),
    CONSTRAINT uq_savings_goal_months_user_goal_month UNIQUE (user_id, goal_id, reference_month)
);

CREATE INDEX idx_savings_goal_months_user_month ON savings_goal_months (user_id, reference_month);
