create table import_history (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    original_filename varchar(255) not null,
    imported_at timestamp with time zone not null,
    row_count integer not null,
    constraint fk_import_history_user foreign key (user_id) references app_users(id)
);

create index idx_import_history_user_imported_at on import_history(user_id, imported_at desc, id desc);
