import { type FormEvent, useEffect, useState } from 'react'
import { createCategory, createCategoryRule, deleteCategory, deleteCategoryRule, getCategories, getCategoryRules } from '../lib/api'
import type { Category, CategoryRule } from '../types/api'

export function CategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([]), [rules, setRules] = useState<CategoryRule[]>([]), [error, setError] = useState<string | null>(null)
  const load = () => Promise.all([getCategories(), getCategoryRules()]).then(([nextCategories, nextRules]) => { setCategories(nextCategories); setRules(nextRules) }).catch(() => setError('Não foi possível carregar categorias e regras.'))
  useEffect(() => { void load() }, [])
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await createCategory(String(form.get('name'))); event.currentTarget.reset(); await load() } catch { setError('Não foi possível criar a categoria.') } }
  async function addRule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await createCategoryRule(String(form.get('keyword')), String(form.get('categoryId'))); event.currentTarget.reset(); await load() } catch { setError('Não foi possível criar a regra.') } }
  return <section className="ledger-page"><header className="page-title"><div><p>Organização</p><h1>Categorias e regras</h1></div></header>{error && <p className="ledger-alert" role="alert">{error}</p>}<div className="two-columns"><section className="ledger-panel"><h2>Categorias</h2><form className="inline-form" onSubmit={addCategory}><label>Nova categoria<input name="name" required /></label><button className="ledger-button">Criar</button></form><ul className="entity-list">{categories.map((category) => <li key={category.id}><span>{category.name}</span><button aria-label={`Excluir ${category.name}`} onClick={async () => { await deleteCategory(category.id); await load() }}>Excluir</button></li>)}</ul></section><section className="ledger-panel"><h2>Regras de classificação</h2><form className="inline-form" onSubmit={addRule}><label>Palavra-chave<input name="keyword" required /></label><label>Categoria<select name="categoryId" required>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><button className="ledger-button">Criar regra</button></form><ul className="entity-list">{rules.map((rule) => <li key={rule.id}><span><strong>{rule.keyword}</strong> → {rule.category.name}</span><button aria-label={`Excluir regra ${rule.keyword}`} onClick={async () => { await deleteCategoryRule(rule.id); await load() }}>Excluir</button></li>)}</ul></section></div></section>
}
