import { type FormEvent, useEffect, useState } from 'react'
import './CategoriesPage.css'
import { applyCategoryRule, createCategory, createCategoryRule, deleteCategory, deleteCategoryRule, getCategories, getCategoryRules } from '../lib/api'
import type { Category, CategoryRule } from '../types/api'

const messageOf = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback

export function CategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([]), [rules, setRules] = useState<CategoryRule[]>([]), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null)
  const load = async () => { setError(null); try { const [nextCategories, nextRules] = await Promise.all([getCategories(), getCategoryRules()]); setCategories(nextCategories); setRules(nextRules) } catch (caught) { setError(messageOf(caught, 'Não foi possível carregar categorias e regras.')) } }
  useEffect(() => { void load() }, [])
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget, form = new FormData(element); try { setError(null); await createCategory(String(form.get('name'))); element.reset(); await load() } catch (caught) { setError(messageOf(caught, 'Não foi possível criar a categoria.')) } }
  async function addRule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget, form = new FormData(element); try { setError(null); await createCategoryRule(String(form.get('keyword')), String(form.get('categoryId'))); element.reset(); await load() } catch (caught) { setError(messageOf(caught, 'Não foi possível criar a regra.')) } }
  const removeCategory = async (id: string | number) => { try { setError(null); await deleteCategory(id); await load() } catch (caught) { setError(messageOf(caught, 'Não foi possível excluir a categoria.')) } }
  const removeRule = async (id: string | number) => { try { setError(null); await deleteCategoryRule(id); await load() } catch (caught) { setError(messageOf(caught, 'Não foi possível excluir a regra.')) } }
  const applyRule = async (rule: CategoryRule) => { if (!window.confirm(`Atualizar transações existentes para a regra “${rule.keyword}”?`)) return; try { setError(null); setNotice(null); const { changedCount } = await applyCategoryRule(rule.id); setNotice(`${changedCount} transações atualizadas.`); await load() } catch (caught) { setError(messageOf(caught, 'Não foi possível atualizar as transações.')) } }
  return <section className="ledger-page"><header className="page-title"><div><p>Organização</p><h1>Categorias e regras</h1></div></header>{error && <p className="ledger-alert" role="alert">{error}</p>}{notice && <p className="ledger-notice" role="status">{notice}</p>}<div className="two-columns"><section className="ledger-panel"><h2>Categorias</h2><form className="inline-form" onSubmit={addCategory}><label>Nova categoria<input name="name" required /></label><button className="ledger-button">Criar</button></form><ul className="entity-list">{categories.map((category) => <li key={category.id}><span>{category.name}</span><button className="ledger-button ledger-button--destructive" aria-label={`Excluir ${category.name}`} onClick={() => void removeCategory(category.id)}>Excluir</button></li>)}</ul></section><section className="ledger-panel"><h2>Regras de classificação</h2><form className="inline-form" onSubmit={addRule}><label>Palavra-chave<input name="keyword" required /></label><label>Categoria<select name="categoryId" required>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><button className="ledger-button">Criar regra</button></form><ul className="entity-list">{rules.map((rule) => <li key={rule.id}><span><strong>{rule.keyword}</strong> → {rule.category.name}</span><span className="rule-actions"><button className="ledger-button ledger-button--secondary" aria-label={`Atualizar transações para ${rule.keyword}`} onClick={() => void applyRule(rule)}>Atualizar transações</button><button className="ledger-button ledger-button--destructive" aria-label={`Excluir regra ${rule.keyword}`} onClick={() => void removeRule(rule.id)}>Excluir</button></span></li>)}</ul></section></div></section>
}
