import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import { getDashboard } from '../lib/api'
import { MovementFilterProvider } from '../lib/movement-filter'
import { DashboardPage } from './DashboardPage'
vi.mock('../lib/api', () => ({ getDashboard: vi.fn() }))
const getDashboardMock = vi.mocked(getDashboard)
const dashboard = (month: string) => ({ totals: { income: 100, expense: 10, balance: 90 }, byCategory: [{ categoryId: 'food', categoryName: `Food ${month}`, spent: 10 }], monthlyEvolution: [{ month, income: 100, expense: 10 }], budgets: [] })
const renderPage = () => render(<MemoryRouter><MovementFilterProvider><DashboardPage /></MovementFilterProvider></MemoryRouter>)
describe('DashboardPage', () => { afterEach(() => vi.clearAllMocks()); it('shows loading then an error when dashboard loading fails', async () => { getDashboardMock.mockRejectedValueOnce(new Error('offline')); renderPage(); expect(screen.getByRole('status')).toHaveTextContent('Carregando painel'); expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível carregar o painel.') }); it('ignores an obsolete month response after a fast month change', async () => { let resolveOld!: (value: ReturnType<typeof dashboard>) => void; const oldRequest = new Promise<ReturnType<typeof dashboard>>((resolve) => { resolveOld = resolve }); getDashboardMock.mockReturnValueOnce(oldRequest).mockResolvedValueOnce(dashboard('2026-09')); renderPage(); fireEvent.change(screen.getByLabelText('Mês'), { target: { value: '2026-09' } }); expect((await screen.findAllByText('Food 2026-09')).length).toBeGreaterThan(0); await act(async () => resolveOld(dashboard('old'))); expect(screen.queryByText('Food old')).not.toBeInTheDocument() }); it('offers statement import when every monthly value is zero', async () => { getDashboardMock.mockResolvedValueOnce({ totals: { income: 0, expense: 0, balance: 0 }, byCategory: [], monthlyEvolution: [{ month: '2026-03', income: 0, expense: 0 }, { month: '2026-04', income: 0, expense: 0 }], budgets: [] }); renderPage(); expect(await screen.findByRole('link', { name: 'Importar extrato' })).toHaveAttribute('href', '/importar') }) })
