import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import { getDashboard, getSavingsGoals, getTransactionTotal } from '../lib/api'
import { MovementFilterProvider } from '../lib/movement-filter'
import { DashboardPage } from './DashboardPage'

vi.mock('../lib/api', () => ({ getDashboard: vi.fn(), getSavingsGoals: vi.fn(), getTransactionTotal: vi.fn() }))
const getDashboardMock = vi.mocked(getDashboard)
const dashboard = (month: string) => ({ totals: { income: 100, expense: 10, balance: 90 }, byCategory: [{ categoryId: 'food', categoryName: `Food ${month}`, spent: 10 }], monthlyEvolution: [{ month, income: 100, expense: 10 }], budgets: [] })
const renderPage = () => render(<MemoryRouter><MovementFilterProvider><DashboardPage /></MovementFilterProvider></MemoryRouter>)

describe('DashboardPage', () => {
  beforeEach(() => { localStorage.clear(); vi.mocked(getSavingsGoals).mockResolvedValue([]); vi.mocked(getTransactionTotal).mockResolvedValue({ total: 0, totalSpent: 0 }) })
  afterEach(() => vi.clearAllMocks())
  it('shows loading then an error when dashboard loading fails', async () => { getDashboardMock.mockRejectedValueOnce(new Error('offline')); renderPage(); expect(screen.getByRole('status')).toHaveTextContent('Carregando painel'); expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível carregar o painel.') })
  it('ignores an obsolete month response after a fast month change', async () => { let resolveOld!: (value: ReturnType<typeof dashboard>) => void; const oldRequest = new Promise<ReturnType<typeof dashboard>>((resolve) => { resolveOld = resolve }); getDashboardMock.mockReturnValueOnce(oldRequest).mockResolvedValueOnce(dashboard('2026-09')); renderPage(); fireEvent.change(screen.getByLabelText('Mês'), { target: { value: '2026-09' } }); expect((await screen.findAllByText('Food 2026-09')).length).toBeGreaterThan(0); await act(async () => resolveOld(dashboard('old'))); expect(screen.queryByText('Food old')).not.toBeInTheDocument() })
  it('offers statement import when every monthly value is zero', async () => { getDashboardMock.mockResolvedValueOnce({ totals: { income: 0, expense: 0, balance: 0 }, byCategory: [], monthlyEvolution: [{ month: '2026-03', income: 0, expense: 0 }, { month: '2026-04', income: 0, expense: 0 }], budgets: [] }); renderPage(); expect(await screen.findByRole('link', { name: 'Importar extrato' })).toHaveAttribute('href', '/importar') })
  it('composes the Monolith dashboard with four financial KPIs', async () => { getDashboardMock.mockResolvedValue(dashboard('2026-08')); renderPage(); expect(await screen.findByRole('region', { name: 'Painel financeiro' })).toBeInTheDocument(); const kpis = screen.getByTestId('monolith-kpi-grid'); expect(kpis).toHaveTextContent('Rendas'); expect(kpis).toHaveTextContent('Despesas'); expect(kpis).toHaveTextContent('Economias'); expect(kpis).toHaveTextContent('Investimentos') })
  it('shows the highest income category and positive amount in income mode', async () => { localStorage.setItem('financial-controller.movement-filter', 'income'); getDashboardMock.mockResolvedValue({ ...dashboard('2026-08'), totals: { income: 100, expense: 0, balance: 100, largestIncome: { categoryId: 1, categoryName: 'Salário', amount: 100 } } }); renderPage(); expect(await screen.findByText('Maior receita')).toBeInTheDocument(); expect(screen.getByText('Salário')).toBeInTheDocument(); expect(screen.getAllByText(/100,00/).length).toBeGreaterThan(0); expect(screen.queryByText('Maior despesa')).not.toBeInTheDocument() })
  it('shows the highest expense category and positive amount in expense mode', async () => { localStorage.setItem('financial-controller.movement-filter', 'expense'); getDashboardMock.mockResolvedValue({ ...dashboard('2026-08'), totals: { income: 0, expense: 90, balance: -90, largestExpense: { categoryId: 2, categoryName: 'Mercado', amount: -90 } } }); renderPage(); expect(await screen.findByText('Maior despesa')).toBeInTheDocument(); expect(screen.getByText('Mercado')).toBeInTheDocument(); expect(screen.getAllByText(/90,00/).length).toBeGreaterThan(0) })
  it('keeps the expense KPI and exposes the income insight in both mode', async () => { getDashboardMock.mockResolvedValue({ ...dashboard('2026-08'), totals: { income: 100, expense: 90, balance: 10, largestIncome: { categoryId: 1, categoryName: 'Salário', amount: 100 }, largestExpense: { categoryId: 2, categoryName: 'Mercado', amount: -90 } } }); renderPage(); expect(await screen.findByText('Maior despesa')).toBeInTheDocument(); expect(screen.getByText('Mercado')).toBeInTheDocument(); expect(screen.getByRole('region', { name: 'Destaques do período' })).toHaveTextContent('Maior receita'); expect(screen.getByRole('region', { name: 'Destaques do período' })).toHaveTextContent('Salário') })
})
