import { render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'
import { MovementFilterProvider } from '../lib/movement-filter'
import { DashboardPage } from './DashboardPage'
import { getDashboard, getSavingsGoals, getTransactionTotal } from '../lib/api'
vi.mock('../lib/api', () => ({ getDashboard: vi.fn(), getSavingsGoals: vi.fn(), getTransactionTotal: vi.fn() }))
it('formats commitment and investment metrics as percentages', async () => { vi.mocked(getDashboard).mockResolvedValue({ totals: { income: 1000, expense: 250, balance: 750, salaryCommittedPercent: 25.5, receivedInvestedPercent: 12 }, byCategory: [{ categoryId: 1, categoryName: 'Casa', spent: 250 }], monthlyEvolution: [{ month: '2026-08', income: 1000, expense: 250 }], budgets: [] }); render(<MemoryRouter><MovementFilterProvider><DashboardPage /></MovementFilterProvider></MemoryRouter>); expect(await screen.findByText('25,50%')).toBeInTheDocument(); expect(screen.getByText('12,00%')).toBeInTheDocument() })
it('aggregates savings goals and shows the investment transaction total in the four KPIs', async () => { vi.mocked(getDashboard).mockResolvedValue({ totals: { income: 1000, expense: 250, balance: 750 }, byCategory: [{ categoryId: 1, categoryName: 'Casa', spent: 250 }], monthlyEvolution: [{ month: '2026-08', income: 1000, expense: 250 }], budgets: [] }); vi.mocked(getSavingsGoals).mockResolvedValue([{ id: 1, name: 'Reserva', targetAmount: 1000, targetDate: null, month: '2026-08', plannedAmount: 100, savedAmount: 200, progressPercent: 20, overallSavedAmount: 200, overallProgressPercent: 20 }, { id: 2, name: 'Viagem', targetAmount: 500, targetDate: null, month: '2026-08', plannedAmount: 50, savedAmount: 75, progressPercent: 15, overallSavedAmount: 75, overallProgressPercent: 15 }]); vi.mocked(getTransactionTotal).mockResolvedValue({ total: 320, totalSpent: 320 }); render(<MemoryRouter><MovementFilterProvider><DashboardPage /></MovementFilterProvider></MemoryRouter>); const kpis = await screen.findByTestId('monolith-kpi-grid'); expect(kpis).toHaveTextContent('R$ 275,00'); expect(kpis).toHaveTextContent('R$ 320,00'); expect(getTransactionTotal).toHaveBeenCalledWith(expect.objectContaining({ type: 'INVESTMENT' })) })
it('shows real savings plans with overall saved total and progress bars', async () => { vi.mocked(getDashboard).mockResolvedValue({ totals: { income: 1000, expense: 250, balance: 750 }, byCategory: [{ categoryId: 1, categoryName: 'Casa', spent: 250 }], monthlyEvolution: [{ month: '2026-08', income: 1000, expense: 250 }], budgets: [] }); vi.mocked(getSavingsGoals).mockResolvedValue([{ id: 1, name: 'Reserva', targetAmount: 1000, targetDate: null, month: '2026-08', plannedAmount: 100, savedAmount: 200, progressPercent: 20, overallSavedAmount: 400, overallProgressPercent: 40 }]); vi.mocked(getTransactionTotal).mockResolvedValue({ total: 0, totalSpent: 0 }); render(<MemoryRouter><MovementFilterProvider><DashboardPage /></MovementFilterProvider></MemoryRouter>); const plans = await screen.findByRole('region', { name: 'Planos de Economia' }); expect(plans).toHaveTextContent('R$ 400,00'); expect(screen.getByRole('progressbar', { name: 'Reserva' })).toHaveAttribute('aria-valuenow', '40'); expect(screen.getByRole('link', { name: 'Ver metas' })).toHaveAttribute('href', '/metas') })
