import { fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { createSavingsGoal, deleteSavingsGoal, getBudgets, getSavingsGoals, updateBudget, updateSavingsGoalMonth } from '../lib/api'
import { AuthProvider } from '../lib/auth'
import { LoginPage } from './LoginPage'
import { GoalsPage } from './GoalsPage'

vi.mock('../lib/api', () => ({ getBudgets: vi.fn(), updateBudget: vi.fn(), getSavingsGoals: vi.fn(), createSavingsGoal: vi.fn(), updateSavingsGoalMonth: vi.fn(), deleteSavingsGoal: vi.fn() }))
const storedSession = { token: 'session-token', user: { id: 1, name: 'Ana', email: 'ana@example.com' } }
const goal = { id: 9, name: 'Reserva', targetAmount: 1000, targetDate: null, month: '2026-08', plannedAmount: 100, savedAmount: 50, progressPercent: 50, overallSavedAmount: 50, overallProgressPercent: 5 }
const renderGoals = () => render(<MemoryRouter initialEntries={['/metas']}><AuthProvider><Routes><Route path="/metas" element={<GoalsPage />} /><Route path="/login" element={<LoginPage />} /></Routes></AuthProvider></MemoryRouter>)

describe('GoalsPage', () => {
  beforeEach(() => { localStorage.clear(); vi.resetAllMocks() })
  afterEach(() => vi.clearAllMocks())
  it('settles authenticated loading when both goal lists are empty', async () => { localStorage.setItem('financial-controller.session', JSON.stringify(storedSession)); vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([]); renderGoals(); expect(await screen.findByRole('heading', { name: 'Objetivos de poupança' })).toBeInTheDocument(); expect(screen.queryByRole('status')).not.toBeInTheDocument() })
  it.each([401, 403])('clears an expired %s session and explains the login redirect', async (status) => { localStorage.setItem('financial-controller.session', JSON.stringify(storedSession)); vi.mocked(getBudgets).mockRejectedValue(Object.assign(new Error('unauthorized'), { status })); vi.mocked(getSavingsGoals).mockResolvedValue([]); renderGoals(); expect(await screen.findByRole('alert')).toHaveTextContent('Sua sessão expirou. Entre novamente.'); expect(localStorage.getItem('financial-controller.session')).toBeNull() })
  it('shows a retry action after a generic load failure and recovers', async () => { vi.mocked(getBudgets).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce([]); vi.mocked(getSavingsGoals).mockResolvedValueOnce([]).mockResolvedValueOnce([]); renderGoals(); expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível carregar as metas.'); fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' })); expect(await screen.findByRole('heading', { name: 'Objetivos de poupança' })).toBeInTheDocument() })
  it('creates a savings objective through the ledger section', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([]); vi.mocked(createSavingsGoal).mockResolvedValue({ ...goal, targetDate: '2026-12-31' }); renderGoals(); await screen.findByRole('heading', { name: 'Objetivos de poupança' }); fireEvent.change(screen.getByLabelText('Nome do objetivo'), { target: { value: 'Reserva' } }); fireEvent.change(screen.getByLabelText('Valor-alvo'), { target: { value: '1000' } }); fireEvent.change(screen.getByLabelText('Data-alvo'), { target: { value: '2026-12-31' } }); fireEvent.click(screen.getByRole('button', { name: 'Novo objetivo' })); expect(await vi.mocked(createSavingsGoal)).toHaveBeenCalledWith({ name: 'Reserva', targetAmount: 1000, targetDate: '2026-12-31' }) })
  it('updates a spending limit', async () => { vi.mocked(getBudgets).mockResolvedValue([{ categoryId: 3, categoryName: 'Casa', spent: 30, limit: 100, exceeded: false }]); vi.mocked(getSavingsGoals).mockResolvedValue([]); vi.mocked(updateBudget).mockResolvedValue({ categoryId: 3, categoryName: 'Casa', spent: 30, limit: 120, exceeded: false }); renderGoals(); fireEvent.change(await screen.findByLabelText('Limite'), { target: { value: '120' } }); fireEvent.click(screen.getByRole('button', { name: 'Salvar' })); expect(await vi.mocked(updateBudget)).toHaveBeenCalledWith(3, expect.any(String), 120) })
  it('saves selected-month planned and saved values', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([goal]); vi.mocked(updateSavingsGoalMonth).mockResolvedValue({ ...goal, plannedAmount: 200, savedAmount: 150 }); renderGoals(); fireEvent.change(await screen.findByLabelText('Planejado para Reserva'), { target: { value: '200' } }); fireEvent.change(screen.getByLabelText('Poupado para Reserva'), { target: { value: '150' } }); fireEvent.click(screen.getByRole('button', { name: 'Salvar mês Reserva' })); expect(await vi.mocked(updateSavingsGoalMonth)).toHaveBeenCalledWith(9, expect.any(String), 200, 150) })
  it('keeps a goal after rejected deletion', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([goal]); vi.mocked(deleteSavingsGoal).mockRejectedValue(new Error('Não foi possível excluir o objetivo.')); renderGoals(); fireEvent.click(await screen.findByRole('button', { name: 'Excluir objetivo Reserva' })); expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível excluir o objetivo.'); expect(screen.getByRole('heading', { name: 'Reserva' })).toBeInTheDocument() })
  it('registers a contribution without changing the monthly planned amount', async () => { const car = { ...goal, name: 'Entrada do carro', targetAmount: 10500, plannedAmount: 300, savedAmount: 0, overallSavedAmount: 500, overallProgressPercent: 4.76, progressPercent: 0 }; vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([car]); vi.mocked(updateSavingsGoalMonth).mockResolvedValue({ ...car, savedAmount: 500, overallSavedAmount: 1000, overallProgressPercent: 9.52, progressPercent: 166.67 }); renderGoals(); fireEvent.click(await screen.findByRole('button', { name: 'Registrar aporte em Entrada do carro' })); expect(screen.getByRole('dialog')).toHaveTextContent('Aporte em Entrada do carro'); fireEvent.change(screen.getByLabelText('Valor do aporte'), { target: { value: '500' } }); expect(screen.getByRole('dialog')).toHaveTextContent('faltam R$ 9.500,00'); fireEvent.click(screen.getByRole('button', { name: 'Confirmar aporte' })); expect(await vi.mocked(updateSavingsGoalMonth)).toHaveBeenCalledWith(9, expect.any(String), 300, 500); expect(await screen.findByRole('status')).toHaveTextContent('Aporte de R$ 500,00 registrado em Entrada do carro. Faltam R$ 9.500,00.') })
})
