import { fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { createSavingsGoal, deleteSavingsGoal, getBudgets, getSavingsGoals, updateBudget, updateSavingsGoalMonth } from '../lib/api'
import { AuthProvider } from '../lib/auth'
import { LoginPage } from './LoginPage'
import { GoalsPage } from './GoalsPage'

vi.mock('../lib/api', () => ({ getBudgets: vi.fn(), updateBudget: vi.fn(), getSavingsGoals: vi.fn(), createSavingsGoal: vi.fn(), updateSavingsGoalMonth: vi.fn(), deleteSavingsGoal: vi.fn() }))
const storedSession = { token: 'session-token', user: { id: 1, name: 'Ana', email: 'ana@example.com' } }
const renderGoals = () => render(<MemoryRouter initialEntries={['/metas']}><AuthProvider><Routes><Route path="/metas" element={<GoalsPage />} /><Route path="/login" element={<LoginPage />} /></Routes></AuthProvider></MemoryRouter>)
const goal = { id: 9, name: 'Reserva', targetAmount: 1000, targetDate: null, month: '2026-08', plannedAmount: 100, savedAmount: 50, progressPercent: 50, overallSavedAmount: 50, overallProgressPercent: 5 }

describe('GoalsPage', () => {
  beforeEach(() => { localStorage.clear(); vi.resetAllMocks() })
  afterEach(() => vi.clearAllMocks())
  it('settles authenticated loading when both goal lists are empty', async () => { localStorage.setItem('financial-controller.session', JSON.stringify(storedSession)); vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([]); renderGoals(); expect(await screen.findByRole('heading', { name: 'Objetivos de poupança' })).toBeInTheDocument(); expect(screen.queryByRole('status')).not.toBeInTheDocument() })
  it.each([401, 403])('clears an expired %s session and explains the login redirect', async (status) => { localStorage.setItem('financial-controller.session', JSON.stringify(storedSession)); vi.mocked(getBudgets).mockRejectedValue(Object.assign(new Error('unauthorized'), { status })); vi.mocked(getSavingsGoals).mockResolvedValue([]); renderGoals(); expect(await screen.findByRole('alert')).toHaveTextContent('Sua sessão expirou. Entre novamente.'); expect(localStorage.getItem('financial-controller.session')).toBeNull() })
  it('shows a retry action after a generic load failure and recovers', async () => { vi.mocked(getBudgets).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce([]); vi.mocked(getSavingsGoals).mockResolvedValueOnce([]).mockResolvedValueOnce([]); renderGoals(); expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível carregar as metas.'); fireEvent.click(screen.getByRole('button', { name: 'Tentar novamente' })); expect(await screen.findByRole('heading', { name: 'Objetivos de poupança' })).toBeInTheDocument() })
  it('updates a goal limit from its page workflow', async () => { vi.mocked(getBudgets).mockResolvedValue([{ categoryId: 3, categoryName: 'Casa', spent: 30, limit: 100, exceeded: false }]); vi.mocked(getSavingsGoals).mockResolvedValue([]); vi.mocked(updateBudget).mockResolvedValue({ categoryId: 3, categoryName: 'Casa', spent: 30, limit: 120, exceeded: false }); renderGoals(); fireEvent.change(await screen.findByLabelText('Limite'), { target: { value: '120' } }); fireEvent.click(screen.getByRole('button', { name: 'Salvar' })); expect(await vi.mocked(updateBudget)).toHaveBeenCalledWith(3, expect.any(String), 120) })
  it('requires a target date before creating a savings objective', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([]); renderGoals(); await screen.findByRole('heading', { name: 'Objetivos de poupança' }); fireEvent.change(screen.getByLabelText('Nome do objetivo'), { target: { value: 'Reserva' } }); fireEvent.change(screen.getByLabelText('Valor-alvo'), { target: { value: '1000' } }); fireEvent.click(screen.getByRole('button', { name: 'Criar objetivo' })); expect(screen.getByLabelText('Data-alvo')).toBeRequired(); expect(createSavingsGoal).not.toHaveBeenCalled() })
  it('creates and shows a savings objective separately from spending limits', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([]); vi.mocked(createSavingsGoal).mockResolvedValue({ ...goal, targetDate: '2026-12-31' }); renderGoals(); await screen.findByRole('heading', { name: 'Objetivos de poupança' }); fireEvent.change(screen.getByLabelText('Nome do objetivo'), { target: { value: 'Reserva' } }); fireEvent.change(screen.getByLabelText('Valor-alvo'), { target: { value: '1000' } }); fireEvent.change(screen.getByLabelText('Data-alvo'), { target: { value: '2026-12-31' } }); fireEvent.click(screen.getByRole('button', { name: 'Criar objetivo' })); expect(await vi.mocked(createSavingsGoal)).toHaveBeenCalledWith({ name: 'Reserva', targetAmount: 1000, targetDate: '2026-12-31' }) })
  it('keeps the create form values and shows a Portuguese error when creation is rejected', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([]); vi.mocked(createSavingsGoal).mockRejectedValue(new Error('Não foi possível criar o objetivo.')); renderGoals(); await screen.findByRole('heading', { name: 'Objetivos de poupança' }); fireEvent.change(screen.getByLabelText('Nome do objetivo'), { target: { value: 'Reserva' } }); fireEvent.change(screen.getByLabelText('Valor-alvo'), { target: { value: '1000' } }); fireEvent.change(screen.getByLabelText('Data-alvo'), { target: { value: '2026-12-31' } }); fireEvent.click(screen.getByRole('button', { name: 'Criar objetivo' })); expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível criar o objetivo.'); expect(screen.getByLabelText('Nome do objetivo')).toHaveValue('Reserva'); expect(screen.getByLabelText('Valor-alvo')).toHaveValue(1000); expect(screen.getByLabelText('Data-alvo')).toHaveValue('2026-12-31') })
  it('saves selected-month planned and saved values then replaces progress', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([goal]); vi.mocked(updateSavingsGoalMonth).mockResolvedValue({ ...goal, plannedAmount: 200, savedAmount: 150, progressPercent: 75, overallSavedAmount: 150, overallProgressPercent: 15 }); renderGoals(); fireEvent.change(await screen.findByLabelText('Planejado para Reserva'), { target: { value: '200' } }); fireEvent.change(screen.getByLabelText('Poupado para Reserva'), { target: { value: '150' } }); fireEvent.click(screen.getByRole('button', { name: 'Salvar mês Reserva' })); expect(await vi.mocked(updateSavingsGoalMonth)).toHaveBeenCalledWith(9, expect.any(String), 200, 150); expect(await screen.findByText(/75%/)).toBeInTheDocument() })
  it('deletes only the selected savings goal and reports rejected deletion in Portuguese', async () => { vi.mocked(getBudgets).mockResolvedValue([]); vi.mocked(getSavingsGoals).mockResolvedValue([goal]); vi.mocked(deleteSavingsGoal).mockRejectedValueOnce(new Error('Não foi possível excluir o objetivo.')).mockResolvedValueOnce(undefined); renderGoals(); fireEvent.click(await screen.findByRole('button', { name: 'Excluir objetivo Reserva' })); expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível excluir o objetivo.'); expect(screen.getByRole('heading', { name: 'Reserva' })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Excluir objetivo Reserva' })); expect(await vi.mocked(deleteSavingsGoal)).toHaveBeenCalledWith(9) })
})
