import { type FormEvent, type KeyboardEvent, useEffect, useLayoutEffect, useRef, useState } from 'react'
import './GoalsPage.css'
import './GoalsPageLayout.css'
import './GoalsPageMonolith.css'
import { useNavigate } from 'react-router-dom'
import { createSavingsGoal, deleteSavingsGoal, getBudgets, getSavingsGoals, updateBudget, updateSavingsGoalMonth } from '../lib/api'
import { useAuth } from '../lib/auth'
import type { Budget, SavingsGoal, SavingsGoalInput } from '../types/api'

const now = () => new Date().toISOString().slice(0, 7)
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
const accessibleMoney = (amount: number) => money.format(amount).replace(/\u00a0/g, ' ')
const monthName = (month: string) => new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(new Date(`${month}-01T12:00:00`))
const focusables = (element: HTMLElement) => [...element.querySelectorAll<HTMLElement>('input:not([disabled]),button:not([disabled])')]
const trapTab = (event: KeyboardEvent<HTMLElement>) => { if (event.key !== 'Tab') return; const controls = focusables(event.currentTarget); const first = controls[0], last = controls[controls.length - 1]; if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } }

export function GoalsPage() {
  const [month, setMonth] = useState(now), [budgets, setBudgets] = useState<Budget[] | null>(null), [goals, setGoals] = useState<SavingsGoal[]>([]), [loadError, setLoadError] = useState(false), [attempt, setAttempt] = useState(0), [newGoal, setNewGoal] = useState(false), [contributionGoal, setContributionGoal] = useState<SavingsGoal | null>(null), [notice, setNotice] = useState('')
  const { clearSession } = useAuth(); const navigate = useNavigate(); const newGoalOrigin = useRef<HTMLButtonElement>(null), contributionOrigin = useRef<HTMLButtonElement>(null)
  useEffect(() => { let cancelled = false; setBudgets(null); setLoadError(false); Promise.all([getBudgets(month), getSavingsGoals(month)]).then(([nextBudgets, nextGoals]) => { if (!cancelled) { setBudgets(nextBudgets); setGoals(nextGoals ?? []) } }).catch((error: { status?: number }) => { if (cancelled) return; if (error.status === 401 || error.status === 403) { clearSession(); navigate('/login', { replace: true, state: { message: 'Sua sessão expirou. Entre novamente.' } }); return } setBudgets([]); setGoals([]); setLoadError(true) }); return () => { cancelled = true } }, [month, attempt])
  useLayoutEffect(() => { if (!newGoal) newGoalOrigin.current?.focus() }, [newGoal])
  useLayoutEffect(() => { if (!contributionGoal) contributionOrigin.current?.focus() }, [contributionGoal])
  const create = async (input: SavingsGoalInput) => { const goal = await createSavingsGoal(input); setGoals((current) => [...current, goal]) }
  const contributionTotal = goals.reduce((sum, goal) => sum + goal.savedAmount, 0)
  const totalBudgetLimit = budgets?.reduce((sum, budget) => sum + Math.abs(budget.limit), 0) ?? 0, totalBudgetSpent = budgets?.reduce((sum, budget) => sum + Math.abs(budget.spent), 0) ?? 0, totalBudgetPercent = totalBudgetSpent / Math.max(totalBudgetLimit, 1) * 100
  return <section className="ledger-page goals-page"><header className="page-title goals-header"><div><p>PLANEJAMENTO</p><h1>Metas</h1><span>Organize limites e dê destino à sua poupança.</span></div><label>Mês<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label></header>{loadError ? <div className="ledger-alert" role="alert">Não foi possível carregar as metas.<button onClick={() => setAttempt((value) => value + 1)}>Tentar novamente</button></div> : !budgets ? <div className="goals-skeleton" role="status" aria-label="Carregando metas"><i /><i /><i /><i /></div> : <><section className="goals-summary" aria-label="Resumo das metas"><p><span>Limites acompanhados</span><strong>{budgets.length}</strong></p><p><span>Metas de poupança</span><strong>{goals.length}</strong></p><p><span>Aporte no mês</span><strong>{money.format(contributionTotal)}</strong></p></section><div className="goals-grid"><section className="goals-section"><header><h2>Limites mensais de gastos</h2><p>Para não extrapolar em {monthName(month)}</p></header>{budgets.length === 0 ? <p className="ledger-empty">Ainda não há limites para este mês.</p> : <><BudgetTotal spent={totalBudgetSpent} limit={totalBudgetLimit} percent={totalBudgetPercent} />{budgets.map((budget) => <BudgetRow budget={budget} month={month} key={budget.categoryId} />)}</>}</section><section className="goals-section savings-section"><header><h2>Objetivos de poupança</h2><button ref={newGoalOrigin} onClick={() => setNewGoal(true)}>Novo objetivo</button></header>{goals.length === 0 && <p className="ledger-empty">Crie o primeiro objetivo para dar destino à sua poupança.</p>}{goals.slice(0, 3).map((goal) => <GoalRow goal={goal} month={month} key={goal.id} onContribution={(origin) => { contributionOrigin.current = origin; setContributionGoal(goal) }} update={(next) => setGoals((current) => current.map((item) => item.id === next.id ? next : item))} remove={(id) => setGoals((current) => current.filter((item) => item.id !== id))} />)}{goals.length > 3 && <p>Ver todos os objetivos</p>}</section></div></>}{notice && <p role="status" aria-live="polite">{notice}</p>}{newGoal && <NewGoalDialog onClose={() => setNewGoal(false)} onCreate={async (input) => { await create(input); setNewGoal(false) }} />}{contributionGoal && <ContributionDialog goal={contributionGoal} month={month} onClose={() => setContributionGoal(null)} onSaved={(updated, amount) => { setGoals((current) => current.map((goal) => goal.id === updated.id ? updated : goal)); setNotice(`Aporte de ${money.format(amount)} registrado em ${updated.name}. Faltam ${money.format(Math.max(0, updated.targetAmount - updated.overallSavedAmount))}.`); setContributionGoal(null) }} />}</section>
}

function BudgetTotal({ spent, limit, percent }: { spent: number; limit: number; percent: number }) { const cappedPercent = Math.min(100, percent); return <article className="goal-row budget-total"><div><h3>Total dos limites mensais</h3><p>{money.format(spent)} de {money.format(limit)}</p></div><div role="progressbar" aria-label="Total dos limites mensais" aria-valuemin={0} aria-valuemax={100} aria-valuenow={cappedPercent} aria-valuetext={`${accessibleMoney(spent)} de ${accessibleMoney(limit)}, ${Math.round(cappedPercent)}%`} className="goal-progress"><i style={{ width: `${cappedPercent}%`, backgroundColor: 'var(--accent-income)' }} /></div></article> }
function BudgetRow({ budget, month }: { budget: Budget; month: string }) { const [limit, setLimit] = useState(String(Math.abs(budget.limit))), [current, setCurrent] = useState(budget); const percent = Math.abs(current.spent) / Math.max(Math.abs(current.limit), 1) * 100; return <article className="goal-row budget-row"><div><h3>{current.categoryName}</h3><p>{money.format(Math.abs(current.spent))} de {money.format(Math.abs(current.limit))}</p></div><div role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, percent)} aria-valuetext={`${current.categoryName}: ${money.format(Math.abs(current.spent))} de ${money.format(Math.abs(current.limit))}, ${Math.round(percent)}%`} className="goal-progress"><i style={{ width: `${Math.min(100, percent)}%` }} /></div><div className="goal-budget-controls"><label>Limite<input value={limit} onChange={(event) => setLimit(event.target.value)} /></label><button className="ledger-button" onClick={async () => setCurrent(await updateBudget(current.categoryId, month, Number(limit)))}>Salvar</button></div></article> }
function GoalRow({ goal, month, update, remove, onContribution }: { goal: SavingsGoal; month: string; update: (goal: SavingsGoal) => void; remove: (id: string | number) => void; onContribution: (origin: HTMLButtonElement) => void }) { const [planned, setPlanned] = useState(String(goal.plannedAmount)), [saved, setSaved] = useState(String(goal.savedAmount)), [error, setError] = useState(''); const save = async () => { try { setError(''); update(await updateSavingsGoalMonth(goal.id, month, Number(planned), Number(saved))) } catch { setError('Não foi possível salvar os valores do objetivo.') } }; const del = async () => { try { setError(''); await deleteSavingsGoal(goal.id); remove(goal.id) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível excluir o objetivo.') } }; return <article className="goal-row"><div><h3>{goal.name}</h3><p>{goal.targetDate}</p><p>{money.format(goal.overallSavedAmount)} de {money.format(goal.targetAmount)} · faltam {money.format(Math.max(0, goal.targetAmount - goal.overallSavedAmount))}</p></div><div role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, goal.overallProgressPercent)} aria-valuetext={`${goal.name}: ${goal.overallProgressPercent}% concluído`} className="goal-progress"><i style={{ width: `${Math.min(100, goal.overallProgressPercent)}%`, backgroundColor: 'var(--accent-income)' }} /></div><p>{monthName(month)}: {money.format(goal.savedAmount)} de {money.format(goal.plannedAmount)}</p><div><button className="ledger-button" aria-label={`Registrar aporte em ${goal.name}`} onClick={(event) => onContribution(event.currentTarget)}>Registrar aporte</button><label>Planejado para {goal.name}<input value={planned} onChange={(event) => setPlanned(event.target.value)} /></label><label>Poupado para {goal.name}<input value={saved} onChange={(event) => setSaved(event.target.value)} /></label><button className="ledger-button ledger-button--secondary" onClick={save}>Salvar mês {goal.name}</button><button className="ledger-button ledger-button--destructive" aria-label={`Excluir objetivo ${goal.name}`} onClick={del}>Excluir</button></div>{error && <p role="alert">{error}</p>}</article> }
function NewGoalDialog({ onClose, onCreate }: { onClose: () => void; onCreate: (input: SavingsGoalInput) => Promise<void> }) { const [error, setError] = useState(''), [saving, setSaving] = useState(false); const input = useRef<HTMLInputElement>(null); useEffect(() => { input.current?.focus() }, []); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); try { setSaving(true); setError(''); await onCreate({ name: String(values.get('name')), targetAmount: Number(values.get('targetAmount')), targetDate: String(values.get('targetDate')) }) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível criar o objetivo.') } finally { setSaving(false) } }; return <div className="ledger-dialog" role="dialog" aria-modal="true" aria-labelledby="new-goal-title" aria-describedby="new-goal-help" onKeyDown={(event) => { trapTab(event); if (event.key === 'Escape' && !saving) onClose() }}><form onSubmit={submit}><h2 id="new-goal-title">Novo objetivo</h2><p id="new-goal-help">Preencha nome, valor-alvo e data-alvo para criar o objetivo.</p><label>Nome do objetivo<input ref={input} name="name" required /></label><label>Valor-alvo<input name="targetAmount" required type="number" /></label><label>Data-alvo<input name="targetDate" required type="date" /></label>{error && <p role="alert">{error}</p>}<button type="button" disabled={saving} onClick={onClose}>Cancelar</button><button type="submit" disabled={saving}>{saving ? 'Criando…' : 'Criar objetivo'}</button></form></div> }
function ContributionDialog({ goal, month, onClose, onSaved }: { goal: SavingsGoal; month: string; onClose: () => void; onSaved: (goal: SavingsGoal, amount: number) => void }) { const [value, setValue] = useState(''), [error, setError] = useState(''), [saving, setSaving] = useState(false); const input = useRef<HTMLInputElement>(null); const amount = Number(value); const valid = Number.isFinite(amount) && amount >= .01 && /^\d+(\.\d{1,2})?$/.test(value); const remaining = Math.max(0, goal.targetAmount - goal.overallSavedAmount - (valid ? amount : 0)); useEffect(() => { input.current?.focus() }, []); const submit = async (event: FormEvent) => { event.preventDefault(); if (!valid) { setError('Informe um valor de aporte válido.'); return } try { setSaving(true); setError(''); const updated = await updateSavingsGoalMonth(goal.id, month, goal.plannedAmount, goal.savedAmount + amount); onSaved(updated, amount) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível registrar o aporte.') } finally { setSaving(false) } }; return <div className="ledger-dialog" role="dialog" aria-modal="true" aria-labelledby="contribution-title" aria-describedby="contribution-context contribution-preview" onKeyDown={(event) => { trapTab(event); if (event.key === 'Escape' && !saving) onClose() }}><form onSubmit={submit}><h2 id="contribution-title">Aporte em {goal.name}</h2><p id="contribution-context">{monthName(month)}. Faltam {money.format(Math.max(0, goal.targetAmount - goal.overallSavedAmount))} para o objetivo</p><label>Valor do aporte<input ref={input} aria-describedby="contribution-preview" inputMode="decimal" min="0.01" step="0.01" required value={value} onChange={(event) => setValue(event.target.value)} /></label><p id="contribution-preview">Após este aporte: faltam {money.format(remaining)}</p>{error && <p role="alert">{error}</p>}<button type="button" disabled={saving} onClick={onClose}>Cancelar</button><button disabled={saving} type="submit">{saving ? 'Registrando…' : 'Confirmar aporte'}</button></form></div> }
