import { type ChangeEvent, useEffect, useState } from 'react'
import { AlertCircle, Eye } from 'lucide-react'
import { getCategories, getTransactionPage } from '../lib/api'
import { useMovementFilter } from '../lib/movement-filter'
import type { Category, TransactionPage } from '../types/api'

const currentMonth = () => new Date().toISOString().slice(0, 7)
const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
export function TransactionsPage() {
  const [month, setMonth] = useState(currentMonth), [categoryId, setCategory] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState(''), [page, setPage] = useState(0), [data, setData] = useState<TransactionPage | null>(null), [categories, setCategories] = useState<Category[]>([]), [error, setError] = useState(false), [retry, setRetry] = useState(0)
  const { filter } = useMovementFilter()
  useEffect(() => { getCategories().then(setCategories).catch(() => setCategories([])) }, [])
  useEffect(() => { let cancelled = false; setData(null); setError(false); getTransactionPage({ month, page, size: 10, type: filter === 'both' ? undefined : filter === 'income' ? 'INCOME' : 'EXPENSE', categoryId: categoryId || undefined, from: from || undefined, to: to || undefined }).then((result) => { if (!cancelled) setData(result) }).catch(() => { if (!cancelled) setError(true) }); return () => { cancelled = true } }, [month, page, filter, categoryId, from, to, retry])
  const resetPage = (setter: (value: string) => void) => (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => { setter(event.target.value); setPage(0) }
  return <section className="ledger-page"><header className="page-title"><div><p>Movimentações</p><h1>Transações</h1></div></header><div className="ledger-filters"><label>Mês<input type="month" value={month} onChange={resetPage(setMonth)} /></label><label>Categoria<select value={categoryId} onChange={resetPage(setCategory)}><option value="">Todas</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>De<input type="date" value={from} onChange={resetPage(setFrom)} /></label><label>Até<input type="date" value={to} onChange={resetPage(setTo)} /></label></div>{error ? <div className="ledger-alert" role="alert"><AlertCircle size={18} />Não foi possível carregar transações.<button onClick={() => setRetry((value) => value + 1)}>Tentar novamente</button></div> : !data ? <p className="ledger-skeleton" role="status">Carregando transações…</p> : data.content.length === 0 ? <p className="ledger-empty">Nenhuma transação encontrada.</p> : <div className="table-wrap"><table className="transaction-table"><caption className="sr-only">Transações filtradas</caption><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Tipo</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{data.content.map((transaction) => { const description = transaction.description ?? transaction.history; return <tr key={transaction.id}><td>{transaction.date}</td><td>{description}{transaction.needsReview && <span className="review-badge">Revisar</span>}</td><td><span className="category-badge">{transaction.category.name}</span></td><td>{transaction.type}</td><td className={transaction.type === 'INCOME' ? 'income' : 'expense'}>{currency.format(transaction.amount)}</td><td><button aria-label={`Ver transação ${description}`} className="transaction-action" type="button"><Eye aria-hidden size={16} />Ver</button></td></tr> })}</tbody></table></div>}{data && data.totalPages > 1 && <nav className="pagination" aria-label="Paginação">{Array.from({ length: data.totalPages }, (_, index) => <button aria-current={index === page ? 'page' : undefined} aria-label={`Página ${index + 1}`} key={index} onClick={() => setPage(index)}>{index + 1}</button>)}</nav>}</section>
}
