import { fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { MovementFilterProvider } from '../lib/movement-filter'
import { getCategories, getTransactionPage, updateTransactionCategory } from '../lib/api'
import { TransactionsPage } from './TransactionsPage'

const mocks = vi.hoisted(() => ({ getTransactionTotal: vi.fn() }))
vi.mock('../lib/api', () => ({ getCategories: vi.fn(), getTransactionPage: vi.fn(), getTransactionTotal: mocks.getTransactionTotal, updateTransactionCategory: vi.fn() }))
const transaction = { id: 7, date: '2026-08-02', history: 'Mercado', description: null, amount: -25, category: { id: 1, name: 'Alimentação' }, type: 'EXPENSE', needsReview: false }
const page = { content: [transaction], page: 0, size: 10, totalElements: 1, totalPages: 1 }
const renderPage = () => render(<MovementFilterProvider><TransactionsPage /></MovementFilterProvider>)

describe('TransactionsPage', () => {
  beforeEach(() => { localStorage.clear(); vi.resetAllMocks(); vi.mocked(getCategories).mockResolvedValue([{ id: 1, name: 'Alimentação' }, { id: 2, name: 'Casa' }]); vi.mocked(getTransactionPage).mockResolvedValue(page); mocks.getTransactionTotal.mockResolvedValue({ total: -25, totalSpent: 25 }) })
  afterEach(() => vi.clearAllMocks())
  it('clears custom dates when a month is chosen and clears month for a complete custom range', async () => { renderPage(); await screen.findByRole('table'); fireEvent.change(screen.getByLabelText('De'), { target: { value: '2026-08-01' } }); expect(screen.getByLabelText('Mês')).toHaveValue(''); fireEvent.change(screen.getByLabelText('Até'), { target: { value: '2026-08-31' } }); expect(mocks.getTransactionTotal).toHaveBeenLastCalledWith({ from: '2026-08-01', to: '2026-08-31', type: undefined, categoryId: undefined }); fireEvent.change(screen.getByLabelText('Mês'), { target: { value: '2026-09' } }); expect(screen.getByLabelText('De')).toHaveValue(''); expect(screen.getByLabelText('Até')).toHaveValue(''); expect(mocks.getTransactionTotal).toHaveBeenLastCalledWith({ month: '2026-09', type: undefined, categoryId: undefined }) })
  it('shows positive total spent for the selected category and movement type', async () => { localStorage.setItem('financial-controller.movement-filter', 'expense'); renderPage(); await screen.findByRole('table'); fireEvent.change(screen.getByLabelText('Categoria'), { target: { value: '2' } }); const label = await screen.findByText('Total gasto no período'); expect(label.parentElement).toHaveTextContent(/R\$.*25,00/); expect(mocks.getTransactionTotal).toHaveBeenLastCalledWith({ month: expect.any(String), type: 'EXPENSE', categoryId: '2' }) })
  it('rejects an invalid custom date range in Portuguese without requesting a total', async () => { renderPage(); await screen.findByRole('table'); mocks.getTransactionTotal.mockClear(); fireEvent.change(screen.getByLabelText('De'), { target: { value: '2026-08-20' } }); fireEvent.change(screen.getByLabelText('Até'), { target: { value: '2026-08-01' } }); expect(await screen.findByRole('alert')).toHaveTextContent('A data inicial não pode ser posterior à data final.'); expect(mocks.getTransactionTotal).not.toHaveBeenCalled() })
  it('guides the user to complete a partial custom range instead of loading forever', async () => { renderPage(); await screen.findByRole('table'); fireEvent.change(screen.getByLabelText('De'), { target: { value: '2026-08-01' } }); expect(await screen.findByText('Informe as duas datas para filtrar por período.')).toBeInTheDocument(); expect(screen.queryByRole('status')).not.toBeInTheDocument() })
  it('reclassifies without learning and opens a detail dialog', async () => { vi.mocked(updateTransactionCategory).mockResolvedValue({ ...transaction, category: { id: 2, name: 'Casa' } }); renderPage(); fireEvent.click(await screen.findByRole('button', { name: 'Editar categoria Mercado' })); fireEvent.change(screen.getByLabelText('Nova categoria para Mercado'), { target: { value: '2' } }); fireEvent.click(screen.getByRole('button', { name: 'Confirmar categoria' })); expect(await vi.mocked(updateTransactionCategory)).toHaveBeenCalledWith(7, 2, false); fireEvent.click(screen.getByRole('button', { name: 'Ver transação Mercado' })); expect(await screen.findByRole('dialog')).toHaveTextContent('Mercado') })
  it('shows positive total spent for category and complete dates without income offset', async () => { mocks.getTransactionTotal.mockResolvedValue({ total: 75, totalSpent: 25 }); renderPage(); await screen.findByRole('table'); fireEvent.change(screen.getByLabelText('Categoria'), { target: { value: '2' } }); const label = await screen.findByText('Total gasto no período'); expect(label.parentElement).toHaveTextContent(/R\$.*25,00/); fireEvent.change(screen.getByLabelText('De'), { target: { value: '2026-08-01' } }); fireEvent.change(screen.getByLabelText('Até'), { target: { value: '2026-08-31' } }); expect(await screen.findByText('Total gasto no período')).toBeInTheDocument(); expect(mocks.getTransactionTotal).toHaveBeenLastCalledWith({ from: '2026-08-01', to: '2026-08-31', type: undefined, categoryId: '2' }) })
})
